version: '3.8'

networks:
  docker-network-localhost:

services:
  
  mysql_localhost:
    container_name: mysql_localhost
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3312:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - docker-network-localhost
      